### ISSUE TITLE
unespected crash

### ISSUE THREAD

**Issue by FerdinandoLM** [jacopofar/ircbotjs#3]
Got this error while running node index.js

TypeError: Cannot read property 'match' of undefined
at Client.send ( /node_modules/irc/lib/irc.js:819:30)
at Client._connectionHandler ( /node_modules/irc/lib/irc.js:647:10 )
at Socket.g (events.js:260:16)
at emitNone (events.js:72:20)
at Socket.emit (events.js:166:7)
at TCPConnectWrap.afterConnect [as oncomplete](net.js:1048:10)

**Comment by jacopofar** [comment]
It seems to be a problem related to the initial configuration. I'll insert a few checks to make the error frendlier.

Can you paste which fields were in the configuration that was used?

**Comment by FerdinandoLM** [comment]
Hi, actually you could close the issue, because with the pull #4 found here https://github.com/jacopofar/ircbotjs/pull/4 , I solved and bugfixed the error. 

There was an error in index.js

**Comment by jacopofar** [comment]
Perfect!
